# Build configuration for checking Wordpress Coding Standards.

pipelines:
  branches:
    '{feature/*,bugfix/*}':
      - step:
          image: tfirdaus/wp-docklines:php5.6-apache
          name: "PHP 5.6"
          script:
            ## Run PHPCS
            - php --version
            - phpcs --version
            - phpcs --standard=WordPress .
      - step:
          image: tfirdaus/wp-docklines:php7.0-apache
          name: "PHP 7.0"
          script:
            ## Run PHPCS
            - php --version
            - phpcs --version
            - phpcs --standard=WordPress .
      - step:
          image: tfirdaus/wp-docklines:php7.1-apache
          name: "PHP 7.1"
          script:
            ## Run PHPCS
            - php --version
            - phpcs --version
            - phpcs --standard=WordPress .
      - step:
          image: tfirdaus/wp-docklines:php7.2-apache
          name: "PHP 7.2"
          script:
            ## Run PHPCS
            - php --version
            - phpcs --version
            - phpcs --standard=WordPress .